name: CI with SonarQube and Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: SonarQube scan
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=django-app
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Enforce Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # Job 2: Trivy Docker image scan with strict security
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t django-app:latest .
        
      - name: Verify Docker image exists
        run: docker images django-app:latest
        
      - name: Run Trivy Scan (Fail on ANY vulnerabilities)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: django-app:latest
          format: table
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          vuln-type: os,library
          exit-code: '1'  # Fail the build if vulnerabilities found
          
      - name: Run Trivy Scan (Generate SARIF report)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: django-app:latest
          format: sarif
          output: trivy-results.sarif
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif